"""empty message

Revision ID: c647e4924c69
Revises: 
Create Date: 2024-09-09 14:54:34.479988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c647e4924c69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Science',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.String(length=64), nullable=True, comment='标签序号'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='名称'),
    sa.Column('type', sa.String(length=64), nullable=True, comment='类型'),
    sa.Column('sub_type', sa.String(length=64), nullable=True, comment='子类型'),
    sa.Column('img', sa.String(length=255), nullable=True, comment='图片地址'),
    sa.Column('intro', sa.Text(), nullable=True, comment='介绍'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Science')
    # ### end Alembic commands ###
